name: Continuous Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Clone api3-dao-dashboard
        uses: actions/checkout@master
      - name: Check hyperlinks
        uses: gaurav-nelson/github-action-markdown-link-check@v1

  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone api3-dao-dashboard
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn lint
      - name: Prepare config
        run: node dev-scripts/copy-localhost-data.js
      - name: Compile
        run: yarn tsc
      - name: Test
        run: yarn test

  cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Clone api3-dao-dashboard
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Cypress
        run: yarn ci:cypress
